apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-model-staging
  namespace: staging
  labels:
    app: ml-model
    environment: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-model
      environment: staging
  template:
    metadata:
      labels:
        app: ml-model
        environment: staging
    spec:
      containers:
      - name: ml-model
        image: ml-model:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: MODEL_PATH
          value: "/opt/ml/model"
        - name: ENVIRONMENT
          value: "staging"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ml-model-staging
  namespace: staging
spec:
  selector:
    app: ml-model
    environment: staging
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
