apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-pipeline
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kathangabani-nyu/MLOps-Project-Group-20
    path: infrastructure
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
