FROM pytorch/pytorch:2.2.0-cuda12.1-cudnn8-runtime

RUN pip install --no-cache-dir \
    ray==2.42.1 \
    mlflow \
    "lightning<2.5.0.post0" \
    "litgpt[all]==0.5.7" \
    datasets \
    peft \
    trl
