apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-model-production
  namespace: production
  labels:
    app: ml-model
    environment: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ml-model
      environment: production
  template:
    metadata:
      labels:
        app: ml-model
        environment: production
    spec:
      containers:
      - name: ml-model
        image: ml-model:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        env:
        - name: MODEL_PATH
          value: "/opt/ml/model"
        - name: ENVIRONMENT
          value: "production"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ml-model-production
  namespace: production
spec:
  selector:
    app: ml-model
    environment: production
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer
